// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain;

import com.nex.domain.Record;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Record_Roo_Configurable {
    
    declare @type: Record: @Configurable;
    
}
