// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain;

import com.nex.domain.Role;

privileged aspect Role_Roo_JavaBean {
    
    public Long Role.getId() {
        return this.id;
    }
    
    public void Role.setId(Long id) {
        this.id = id;
    }
    
    public String Role.getCode() {
        return this.code;
    }
    
    public void Role.setCode(String code) {
        this.code = code;
    }
    
}
