// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.localized;

import com.nex.domain.localized.Type;
import com.nex.domain.localized.TypeText;

privileged aspect TypeText_Roo_JavaBean {
    
    public Long TypeText.getId() {
        return this.id;
    }
    
    public void TypeText.setId(Long id) {
        this.id = id;
    }
    
    public Type TypeText.getLocalizable() {
        return this.localizable;
    }
    
    public void TypeText.setLocalizable(Type localizable) {
        this.localizable = localizable;
    }
    
}
