// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.localized;

import com.nex.domain.localized.Type;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Type_Roo_Jpa_Entity {
    
    declare @type: Type: @Entity;
    
    declare @type: Type: @Table(name = "record_type");
    
}
