// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.localized;

import com.nex.domain.localized.TypeText;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect TypeText_Roo_Jpa_Entity {
    
    declare @type: TypeText: @Entity;
    
    declare @type: TypeText: @Table(name = "record_type_text");
    
}
