// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.localized;

import com.nex.domain.localized.Type;
import com.nex.domain.localizedfield.LocalizedField;
import java.util.List;

privileged aspect Type_Roo_JavaBean {
    
    public Long Type.getId() {
        return this.id;
    }
    
    public void Type.setId(Long id) {
        this.id = id;
    }
    
    public List<LocalizedField> Type.getLocalizedTexts() {
        return this.localizedTexts;
    }
    
    public void Type.setLocalizedTexts(List<LocalizedField> localizedTexts) {
        this.localizedTexts = localizedTexts;
    }
    
}
