// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain.localized;

import com.nex.domain.localized.Type;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Type_Roo_Configurable {
    
    declare @type: Type: @Configurable;
    
}
