// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nex.domain;

import com.nex.domain.Language;

privileged aspect Language_Roo_JavaBean {
    
    public String Language.getId() {
        return this.id;
    }
    
    public void Language.setId(String id) {
        this.id = id;
    }
    
    public String Language.getName() {
        return this.name;
    }
    
    public void Language.setName(String name) {
        this.name = name;
    }
    
}
